### ISSUE TITLE
Multiple window incompatibility

### ISSUE THREAD

**Issue by Selians** [dahoares/auto-tab-grouper#1]
Multiple windows get merged into one when tab grouper detects a new tab to put in a group. DM me for more info

**Comment by Selians** [comment]
Solved by using the "Group tabs across windows" button

**Comment by dahoares** [comment]
Support grouping tabs across windows (commit #7424d3e)

- Create separate groups for tabs in different windows when the option is disabled.
- Group tabs together across windows when the option is enabled.

**Comment by dahoares** [comment]
fixed with commit #7424d3e

- Create separate groups for tabs in different windows when the option "group tabs across windows" is disabled.
- Group groups together across windows when the option "group tabs across windows" is enabled.
